# model = "gpt-5.3-codex"
# model_reasoning_effort = "high"
# personality = "pragmatic"

# [mcp_servers.context7]
# url = "https://mcp.context7.com/mcp"

# [mcp_servers.context7.http_headers]
# CONTEXT7_API_KEY = "ctx7sk-3016d3c1-23e1-4fdb-96b3-289a41da4cf8"

# [mcp_servers.chrome-devtools]
# command = "npx"
# args = ["chrome-devtools-mcp@latest"]

# [mcp_servers.playwright]
# args = ["@playwright/mcp@latest"]
# command = "npx"

# [mcp_servers.notion]
# url = "https://mcp.notion.com/mcp"
