import js from "@eslint/js";
import jest from "eslint-plugin-jest";

const runtimeGlobals = {
  console: "readonly",
  window: "readonly",
  document: "readonly",
  navigator: "readonly",
  performance: "readonly",
  Image: "readonly",
  FileReader: "readonly",
  Blob: "readonly",
  URL: "readonly",
  setTimeout: "readonly",
  clearTimeout: "readonly",
  setInterval: "readonly",
  clearInterval: "readonly",
  requestAnimationFrame: "readonly",
  localStorage: "readonly",
  fetch: "readonly",
  CustomEvent: "readonly",
  MouseEvent: "readonly",
  KeyboardEvent: "readonly",
  TouchEvent: "readonly",
  HTMLElement: "readonly",
  HTMLCanvasElement: "readonly",
  Element: "readonly",
  AudioContext: "readonly",
  webkitAudioContext: "readonly",
  AudioBufferSourceNode: "readonly",
  AudioNode: "readonly",
  WebSocket: "readonly",
  XMLHttpRequest: "readonly",
  Worker: "readonly",
  exports: "writable",
  module: "readonly",
  require: "readonly",
  process: "readonly",
  global: "readonly",
  globalThis: "readonly",
  __dirname: "readonly",
  __filename: "readonly",
};

const litegraphGlobals = {
  gl: "readonly",
  GL: "readonly",
  LS: "readonly",
  Uint8Array: "readonly",
  Uint32Array: "readonly",
  Float32Array: "readonly",
  LGraphCanvas: "readonly",
  LGraph: "readonly",
  LGraphNode: "readonly",
  LiteGraph: "readonly",
  LGraphTexture: "readonly",
  Mesh: "readonly",
  Shader: "readonly",
  enableWebGLCanvas: "readonly",
  vec2: "readonly",
  vec3: "readonly",
  vec4: "readonly",
  DEG2RAD: "readonly",
  isPowerOfTwo: "readonly",
  cloneCanvas: "readonly",
  createCanvas: "readonly",
  hex2num: "readonly",
  colorToString: "readonly",
  showElement: "readonly",
  quat: "readonly",
  AudioSynth: "readonly",
  SillyClient: "readonly",
};

const baseRules = {
  "no-console": "off",
  "no-undef": "off",
  "no-useless-assignment": "off",
  "no-self-assign": "off",
  "no-fallthrough": "off",
  "no-empty": "warn",
  "no-redeclare": "warn",
  "no-inner-declarations": "warn",
  "no-constant-condition": "warn",
  "no-unused-vars": "warn",
  "no-mixed-spaces-and-tabs": "warn",
  "no-unreachable": "warn",
  curly: ["warn", "all"],
};

const jestRecommended = jest.configs["flat/recommended"];

export default [
  {
    ignores: [
      "node_modules/**",
      "build/**",
      "dist/**",
      "doc/**",
      "coverage/**",
      "editor/temp-dist/**",
    ],
  },
  {
    files: ["src/**/*.js", "editor/**/*.js", "tests/**/*.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "script",
      globals: {
        ...runtimeGlobals,
        ...litegraphGlobals,
      },
    },
    rules: baseRules,
  },
  {
    files: ["scripts/**/*.mjs"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: runtimeGlobals,
    },
    rules: baseRules,
  },
  {
    ...jestRecommended,
    files: ["tests/**/*.js"],
    languageOptions: {
      ...jestRecommended.languageOptions,
      ecmaVersion: "latest",
      sourceType: "script",
      globals: {
        ...(jestRecommended.languageOptions?.globals || {}),
        ...runtimeGlobals,
        ...litegraphGlobals,
      },
    },
  },
];
